name: Auto Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js v16.20.2
      uses: actions/setup-node@v4
      with:
        node-version: 16.20.2
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: CI=false npm run build

    - name: Deploy with gh-pages
      run: |
        git config --global user.email "github-actions-bot@users.noreply.github.com"
        git config --global user.name "github-actions-bot"
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
